game: skyrim
imports:
    - D:\Documents\Projects\SCX\SCX\Scripts\Source
    - D:\Games\Mod Organizer 2 Skyrim\mods\JContainers\scripts\source
    - D:\Games\Mod Organizer 2 Skyrim\mods\RaceMenu Unpacked\scripts\source
    - D:\Games\Mod Organizer 2 Skyrim\mods\SexLab Inflation Framework\Scripts\Source\SexLab Inflation Framework
    - D:\Games\Mod Organizer 2 Skyrim\mods\SkyUI_5.1_SDK\Scripts\Source
    - D:\Games\Mod Organizer 2 Skyrim\mods\PapyrusUtil - Modders Scripting Utility Functions\scripts\Source
    - D:\Games\Mod Organizer 2 Skyrim\mods\UI Extensions Extracted\scripts\source
    - D:\Games\Mod Organizer 2 Skyrim\mods\Mfg Console\scripts\source
    - D:\Games\SteamLibrary\steamapps\common\Skyrim\Data\Scripts\Source
    - D:\Games\SteamLibrary\steamapps\common\Skyrim\Data\Scripts\Source\Dawnguard
    - D:\Games\SteamLibrary\steamapps\common\Skyrim\Data\Scripts\Source\Dragonborn
    - D:\Games\SteamLibrary\steamapps\common\Skyrim\Data\Scripts\Source\Hearthfire
output: D:\Documents\Projects\SCX\SCX\Scripts\
optimize: true
